// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class AgvWork
{
    public int Id { get; set; }

    public int? AgvType { get; set; }

    public int? Status { get; set; }

    public string AgvWork1 { get; set; }

    public DateTime? DateRun { get; set; }
}