// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class Area
{
    public int Id { get; set; }

    public string AreaCode { get; set; }
    public string? AreaName { get; set; }

    public int? Row { get; set; }

    public int? WarehouseId { get; set; }
}