// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class Employee
{
    public int Id { get; set; }

    public string EmployeeCode { get; set; }

    public string FullName { get; set; }
}