// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class ExportWarehouse
{
    public int Id { get; set; }

    public int? Stt { get; set; }

    public string ExportCode { get; set; }

    public int? WarehouseId { get; set; }

    public int? EmployeeId { get; set; }

    public int? Status { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public DateTime? ExportWarehouseDate { get; set; }

    public int? StatusPriority { get; set; }

    public DateTime? CreateDatePriority { get; set; }
}