// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class ImportWarehouseDetail
{
    public int Id { get; set; }

    public int? ImportWarehouseId { get; set; }

    public int? MaterialId { get; set; }

    public int? Status { get; set; }

    public int? Quantity { get; set; }

    public int? Stt { get; set; }

    public int? PositionId { get; set; }

    public int? StatusAgv { get; set; }

    public DateTime? RequestDate { get; set; }
}