// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class ImportWarehouse
{
    public int Id { get; set; }

    public int? Stt { get; set; }

    public string ImportCode { get; set; }

    public int? WarehouseId { get; set; }

    public int? EmployeeId { get; set; }

    public int? Status { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public DateTime? ImportWarehouseDate { get; set; }

    public int? ExportWarehouseId { get; set; }

    public int? ImportType { get; set; }
}