// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class Material
{
    public int Id { get; set; }

    public int? Stt { get; set; }

    public string MaterialCode { get; set; }

    public string MaterialName { get; set; }

    public int? UnitId { get; set; }

    public int? WarehouseId { get; set; }

    public int? TonDau { get; set; }

    public int? Nhap { get; set; }

    public int? Xuat { get; set; }

    public int? TonCuoi { get; set; }

    public string Note { get; set; }

    public string CreatedBy { get; set; }

    public DateTime? CreatedDate { get; set; }

    public string UpdatedBy { get; set; }

    public DateTime? UpdatedDate { get; set; }

    public int? Inventory { get; set; }

    public int? PositionId { get; set; }
}