// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class Position
{
    public int Id { get; set; }

    public string PositionCode { get; set; }

    public string PositionName { get; set; }

    public int? AreaId { get; set; }
}