// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BMS.Models
{
    public partial class spGetPositionItemResult
    {
        [StringLength(200)]
        public string PositionName { get; set; }
        [StringLength(100)]
        public string PositionCode { get; set; }
        public int? PositionID { get; set; }
    }
}
