// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BMS.Models
{
    public partial class spGetImportWarehouseByIDResult
    {
        public int ID { get; set; }
        public int? STT { get; set; }
        [StringLength(150)]
        public string ImportCode { get; set; }
        public int? WarehouseID { get; set; }
        public int? EmployeeID { get; set; }
        public int? Status { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public DateTime? ImportWarehouseDate { get; set; }
        public int? ExportWarehouseID { get; set; }
        public int? ImportType { get; set; }
        public int? MaterialID { get; set; }
        public int? Quantity { get; set; }
        public int? Row { get; set; }
        [StringLength(50)]
        public string PositionCode { get; set; }
        public int? PositionID { get; set; }
        [StringLength(50)]
        public string MaterialCode { get; set; }
        [StringLength(150)]
        public string MaterialName { get; set; }
    }
}
