// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BMS.Models
{
    public partial class spGetPositionOfAllMaterialResult
    {
        public int ID { get; set; }
        public int? STT { get; set; }
        [StringLength(50)]
        public string MaterialCode { get; set; }
        [StringLength(150)]
        public string MaterialName { get; set; }
        public int? UnitID { get; set; }
        public int? WarehouseID { get; set; }
        public int? TonDau { get; set; }
        public int? Nhap { get; set; }
        public int? Xuat { get; set; }
        public int? TonCuoi { get; set; }
        [StringLength(250)]
        public string Note { get; set; }
        [StringLength(100)]
        public string CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        [StringLength(100)]
        public string UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? Inventory { get; set; }
        public int? PositionID { get; set; }
        [StringLength(50)]
        public string PositionName { get; set; }
        [StringLength(50)]
        public string PositionCode { get; set; }
        [StringLength(150)]
        public string AreaCode { get; set; }
        public int? Row { get; set; }
        public int? StockQuantity { get; set; }
    }
}
