// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace BMS.Models
{
    public partial class spGetQuantityOfMaterialInWarehouseResult
    {
        public int ID { get; set; }
        [StringLength(50)]
        public string MaterialCode { get; set; }
        public int? StockQuantity { get; set; }
        [StringLength(50)]
        public string PositionName { get; set; }
        [StringLength(50)]
        public string PositionCode { get; set; }
        [StringLength(150)]
        public string AreaCode { get; set; }
        public int? Row { get; set; }
    }
}
