// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BMS.Models;

public partial class Unit
{
    public int Id { get; set; }

    public string UnitCode { get; set; }

    public string UnitName { get; set; }
}